In [1]:
import pandas as pd
import numpy as np

In [21]:
n_trials = 10000

# 1

How likely is it that you roll doubles when rolling two dice?

In [185]:
n_dice = 2

# roll two six sided dice n_trials times
rolls = pd.DataFrame(np.random.randint(1, 7, size = (n_trials, n_dice)))
rolls

0  1
0     5  2
1     6  5
2     4  5
3     4  6
4     6  2
...  .. ..
9995  1  3
9996  2  3
9997  1  4
9998  2  3
9999  4  6

[10000 rows x 2 columns]

In [186]:
# for each row check if the first die and second are the same value
doubles = rolls.apply(lambda row: row[0] == row[1], axis = 1)
doubles.mean()

0.1686

# 2

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [188]:
n_coins = 8

# flip 8 coins n_trials times, 1 is heads, 0 is tails
coin_flips = np.random.choice([1, 0], size = (n_trials, n_coins))
coin_flips

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 1],
       [1, 1, 1, ..., 0, 0, 1]])

In [189]:
# sum each row to determine the number of heads flipped
exactly_three_heads = coin_flips.sum(axis = 1) == 3
exactly_three_heads.mean()

0.2228

In [190]:
more_than_three_heads = coin_flips.sum(axis = 1) > 3
more_than_three_heads.mean()

0.6313

# 3

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [191]:
n_billboards = 2

# generate two billboards n_trials times, 1 is data science, 0 is web dev
billboards = np.random.choice([1, 0, 0, 0], size = (n_trials, n_billboards))
billboards

array([[0, 1],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 1]])

In [192]:
both_data_science = billboards.sum(axis = 1) == 2
both_data_science.mean()

0.0641

# 4

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [193]:
n_poptarts_restocked = 17
avg_poptarts_purchased = 3
std_dev = 1.5

# Not including Friday
n_days = 4

# generate poptart sells for four days n_trials times
poptarts = np.random.normal(avg_poptarts_purchased, std_dev, size = (n_trials, n_days))
poptarts

array([[2.78924615, 6.44593021, 2.72861806, 5.05449614],
       [0.91814569, 3.44135478, 3.23739227, 3.46782837],
       [1.44856413, 3.7600609 , 5.32914709, 5.26199545],
       ...,
       [0.89606928, 2.74683886, 3.00364439, 4.5887542 ],
       [1.19811119, 2.07074298, 3.49115605, 3.99156221],
       [3.52740824, 2.4695962 , 3.9914521 , 3.40247909]])

In [195]:
# determine how often there is at least one poptart remaining
at_least_one_poptart_remaining = poptarts.sum(axis = 1) <= n_poptarts_restocked - 1
at_least_one_poptart_remaining.mean()

0.907

# 5

Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [196]:
avg_height_men = 178
std_dev_men = 8
avg_height_women = 170
std_dev_women = 6

# generate heights for men and women n_trials times
heights_of_men = np.random.normal(avg_height_men, std_dev_men, size = n_trials)
heights_of_women = np.random.normal(avg_height_women, std_dev_women, size = n_trials)

In [197]:
# determine the number of times a woman is taller than a man
women_taller_than_men = heights_of_women > heights_of_men
women_taller_than_men.mean()

0.2084

# 6

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [214]:
def probability_no_corrupted_install(n_students):
    p_corrupted_install = 1 / 250
    anaconda_installs = np.random.choice([1, 0], 
                                         p = [p_corrupted_install, 1 - p_corrupted_install], 
                                         size = (n_trials, n_students))

    corrupted_installs = anaconda_installs.sum(axis = 1) >= 1
    return corrupted_installs.mean()

In [215]:
probability_corrupted_install(50)

0.12

In [209]:
probability_corrupted_install(100)

0.3376

In [210]:
probability_corrupted_install(150)

0.4568

In [211]:
probability_corrupted_install(450)

0.8339

In [213]:
n_simulations = 100_000
n_trials = 50
p = 1/250  # probability of an install failure

# 1 = failure during install, 0 = successful install
results = pd.DataFrame(np.random.choice([1, 0], 
                                        p=[p, 1-p], 
                                        size=n_simulations*n_trials).reshape(n_simulations, n_trials))

no_failures = results.apply(lambda row: 1 not in row.values, axis=1)
no_failures.mean()

0.81811

In [219]:
p_corrupted_install = 1 / 250
anaconda_installs = np.random.choice([1, 0], 
                                         p = [p_corrupted_install, 1 - p_corrupted_install], 
                                         size = (n_trials, n_students))

# corrupted_installs = anaconda_installs.sum(axis = 1) >= 1
# corrupted_installs.mean()
anaconda_installs

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])